name: Dart Conventional Release
description: Automating version bump for conventional dart releases
runs:
  using: docker
  image: Dockerfile
branding:
  icon: upload-cloud
  color: blue
inputs:
  github-token:
    description: 'Github token'
    required: true
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: 'v'
    required: false
  script-pre-run:
    description: 'Path to a dart script that is executed before the version bump'
    required: false
